service: authorize # NOTE: update this with your service name
# plugins:
#   - serverless-offline
# custom:
#   serverless-offline:
#     port: 4000
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    LAYER_COMMON_ARN: ${file(./serverless.env.yml):${self:provider.stage}.LAYER_COMMON_ARN}
functions:
  auth:
    handler: src/auth.authorize
    # layers:
    #   - ${env: LAYER_COMMON_ARN}
  privateTest:
    handler: src/handler.privateEndpoint
    events:
      - http:
          path: api/private
          method: get
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token