service: serverless-layer # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
layers:
  commonLibs:
    path: common
    compatibleRuntimes:
      - nodejs10.x
